# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-20 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parents',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student_personal_massage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='update_massage',
            options={},
        ),
    ]
