# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_personal_massage',
            name='family_address',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='家庭住址'),
        ),
    ]
