# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-01 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_personal_massage',
            old_name='student_id',
            new_name='stu_id',
        ),
    ]
