# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-24 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180322_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_personal_massage',
            name='student_id',
            field=models.CharField(max_length=8, verbose_name='学号'),
        ),
    ]
